---
- name: "grub | Deploy grub default configuration"
  ansible.builtin.template:
    src: "grub.j2"
    dest: "/etc/default/grub"
    owner: "root"
    group: "root"
    mode: "0644"
    validate:
      "{{ hostvars[inventory_hostname]['grub_mkconfig_command'] + ' %s' }}"
  notify:
    - "Deploy grub.conf"
