---
- name: "grub | Include pre requisite tasks"
  ansible.builtin.import_tasks:
    file: "pre_requisite.yml"
- name: "grub | Include grub deployment tasks"
  ansible.builtin.include_tasks:
    file: "deploy.yml"
  when:
    - "hostvars[inventory_hostname]['grub'] is defined"
    - "hostvars[inventory_hostname]['grub'] != ''"
