---
- ansible.builtin.import_tasks:
    file: "pre_requisite.yml"
- ansible.builtin.include_tasks:
    file: "deploy_grub.yml"
  when:
    - "hostvars[inventory_hostname]['grub'] is defined"
    - "hostvars[inventory_hostname]['grub'] != ''"
