---
- name: grub | Add the OS specific variables
  include_vars: "{{ hostvars[inventory_hostname]['ansible_os_family'] +
                    '.yml' }}"
- name: grub | Check grub-mkconfig binary
  command: "{{ hostvars[inventory_hostname]['grub_mkconfig_command'] +
               ' --version' }}"
  register: "grub_rc"
- name: grub | Assert that grub-mkconfig is present
  assert:
    that:
    - "grub_rc.rc == 0"
    msg: "'grub-mkconfig' not found."
    quiet: "true"
