---
- name: grub | Add the OS specific variables
  ansible.builtin.include_vars:
    file: "{{ hostvars[inventory_hostname]['ansible_os_family'] + '.yml' }}"
- name: grub | Check grub-mkconfig binary
  ansible.builtin.command:
    cmd: "{{ hostvars[inventory_hostname]['grub_mkconfig_command'] +
      ' --version' }}"
  register: "grub_rc"
- name: grub | Assert that grub-mkconfig is present
  ansible.builtin.assert:
    that:
      - "grub_rc['rc'] == 0"
    msg: "'grub-mkconfig' binary not found."
    quiet: "true"
